# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-11 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
