# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-15 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to='book_images'),
        ),
    ]
