# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-15 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20200315_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
